create database school;
use school;
create table student(student_id int,student_name varchar(20),age int,course varchar(10));
describe student;
show tables;
alter table student add email varchar(20);
show databases;
alter table student modify age smallint;
alter table student modify email varchar(30);
alter table student change student_name fullname varchar(20);
alter table student rename to students;
describe students;
alter table students drop column email;
create table staff(staffid int);
show tables;
drop table staff;
describe students;
alter table students rename column fullname to full_name;
describe students;
