use bca_students;
select * from bca;
alter table bca  add place varchar(25),add mail_id varchar(25) after name;
select name from bca;
select * from bca;
select name,mark from bca;
create table bba(id int,name varchar(20),DOB date, mark int,gender varchar(20));
select *  from bca where mark>50;
select * from bca where gender="male";
select * from bca where name="ilyas";
select * from bca where gender="male" and mark>75;
select * from bca where gender="male" or mark>75;
select* from bca where mark between 55  and 80;
alter table bca rename column name to f_name ;
select * from bca;
select *from bca where id=5;
delete from bca where id=3;
set sql_safe_updates=false;
create table ba(id int primary key,name varchar(20) not null ,DOB date, mark int,gender varchar(20));
select * from bca;
update bca set class="second" where id=4;
select * from bca;
update bca set mail_id="ilyas@gmail.com" where id=1;
select * from bca;
