use bca_students;
create table company(id int,dept_id int,name varchar(20),city varchar(20),salary int);
describe company;
insert into company values(1,1014,"Ajay","Bangalore",58000);
insert into company values(2,1014,"Harry","Delhi",29001);
insert into company values(3,1003,"Anjali","mangalore",34000);
insert into company values(4,1003,"Rahul","Bangalore",54000);
insert into company values(5,1003,"Anisha","Bangalore",67000);
insert into company values(6,1003,"Rajni","Chennai",56000);
insert into company values(7,1003,"Zaid","Bangalore",29000);
insert into company values(8,1003,"Bob","Mumbai",87000);
insert into company values(9,1003,"Raj","Bangalore",45000);
insert into company values(10,1003,"Arya","Chennai",64000);
select*from company;
select*from company order by name desc;
select* from company where name="rahul";
select* from company where salary>=60000;
update company set city="Kannur" where id=8;
set sql_safe_updates=false;
select* from company;
select name,city from company;
update company set city="delhi" where City="bangalore";
select * from company;
select max(salary) from company;
select min(salary) as "maximum salary" from company;
select avg(salary) as "average salery" from company;
select sum(salary) as "total salery" from company;
select count(*) from company;
select city,count(*) from company group by city;
select name from company where name like "a%";
select name from company where name like "%a";
select name from company where name like "%a%";
select name from company where name like "_a%";
select name from company where name like "___";
select * from company where city in("delhi","chennai","kannur");
